#!/usr/bin/env node
// DAG → Lean, one `def` per distinct node: the Lean term is the DAG, not its expansion.
//
//   node dag2lean.mjs <namespace> <name>=<file.dag>... > Trees.lean
//
// Each file is a value (`conventions/README.md`): a line that would reduce is an error. Nodes are
// hash-consed across files as `t<n>`, in dependency order; `<name>` is its file's root.

import { readFileSync } from 'node:fs';

const [ns, ...inputs] = process.argv.slice(2);
if (!ns || !inputs.length) {
  console.error('usage: dag2lean.mjs <namespace> <name>=<file.dag>...');
  process.exit(2);
}

const defs = [];            // Lean source lines, in dependency order
const interned = new Map(); // `.stem t3` / `.fork t3 .leaf` → the def naming it
// A node is `{ stem }` or `{ fork }` with its children, named only once something refers to it:
// a stem the DAG builds merely to apply it to a fork's right child is no node of the value.
const leaf = {};
const intern = (shape) => {
  if (!interned.has(shape)) {
    interned.set(shape, `t${interned.size + 1}`);
    defs.push(`def ${interned.get(shape)} : Value := ${shape}`);
  }
  return interned.get(shape);
};
const ref = (node) => node === leaf ? '.leaf' : node.name;
// Children before parents, left before right — with a stack of its own rather than JavaScript's,
// which a long list (a string constant, say) is deeper than.
const expr = (root) => {
  const todo = [root];
  while (todo.length) {
    const node = todo.at(-1);
    const kids = ref(node) ? [] : (node.fork ?? [node.stem]).filter((kid) => !ref(kid));
    if (kids.length) todo.push(...kids.reverse());
    else if (todo.pop() !== leaf) node.name ??= intern(node.fork
      ? `.fork ${ref(node.fork[0])} ${ref(node.fork[1])}` : `.stem ${ref(node.stem)}`);
  }
  return ref(root);
};

const roots = inputs.map((arg) => {
  const eq = arg.indexOf('=');
  const [name, file] = [arg.slice(0, eq), arg.slice(eq + 1)];
  const env = new Map([['△', leaf]]);
  const get = (id) => env.get(id) ?? (() => { throw new Error(`${file}: unbound ${id}`); })();
  let root;
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const words = line.trim().split(/\s+/).filter(Boolean);
    if (words.length === 3) {
      const [f, x] = [get(words[1]), get(words[2])];
      if (f === leaf) env.set(words[0], { stem: x });
      else if (f.stem) env.set(words[0], { fork: [f.stem, x] });
      else throw new Error(`${file}: \`${line}\` reduces — not a normal form`);
    } else if (words.length === 2) env.set(words[0], get(words[1]));
    else if (words.length === 1) root = get(words[0]);
  }
  if (!root) throw new Error(`${file}: no value line`);
  return `/-- \`${file.split('/').pop()}\` -/\ndef ${name} : Value := ${expr(root)}`;
});

console.log(`-- Generated by dag2lean.mjs; do not edit.
import TreeCalculus.Value

namespace ${ns}
open TreeCalculus

${defs.join('\n')}

${roots.join('\n\n')}

end ${ns}`);
