-- Generated by jets/embed.mjs; do not edit.
import TreeCalculus.Jets

namespace TreeCalculus.Jets

/-- The jets `implementation/cpp/jets.hpp` embeds, as the transitions the runtime takes. -/
def runtimeJets (s t : State Tree) : Prop :=
  DropJet skipLine [newline] s t

/-- The runtime, with its memo and exactly these jets, returns what the reduction rules say. -/
theorem runtimeJets_sound (hm : m.Sound)
    (h : Star (RStep runtimeJets) ⟨.reduce a b [], [], m⟩ ⟨.dispatch r [], [], m'⟩) :
    Run a b r ∧ m'.Sound :=
  runtime_sound (fun _ _ h => DropJet.reaches skipLine_check h) hm h

end TreeCalculus.Jets
