-- Generated by dag2lean.mjs; do not edit.
import TreeCalculus.Tree

namespace TreeCalculus.Jets
open TreeCalculus

def t1 : Tree := .stem .leaf
def t2 : Tree := .fork t1 .leaf
def t3 : Tree := .fork .leaf t2
def t4 : Tree := .fork t1 t3
def t5 : Tree := .fork .leaf t4
def t6 : Tree := .fork t1 t2
def t7 : Tree := .fork .leaf t6
def t8 : Tree := .fork t1 t7
def t9 : Tree := .fork .leaf .leaf
def t10 : Tree := .fork .leaf t9
def t11 : Tree := .fork t1 t9
def t12 : Tree := .fork t11 t10
def t13 : Tree := .fork .leaf t12
def t14 : Tree := .fork t9 t13
def t15 : Tree := .fork t14 .leaf
def t16 : Tree := .fork .leaf t15
def t17 : Tree := .stem t16
def t18 : Tree := .fork t13 t10
def t19 : Tree := .fork t17 t18
def t20 : Tree := .fork t10 t19
def t21 : Tree := .fork .leaf t20
def t22 : Tree := .fork t9 t21
def t23 : Tree := .fork t22 .leaf
def t24 : Tree := .fork .leaf t23
def t25 : Tree := .stem t24
def t26 : Tree := .fork t25 t12
def t27 : Tree := .fork t10 t26
def t28 : Tree := .fork .leaf t27
def t29 : Tree := .fork t9 t28
def t30 : Tree := .fork t29 .leaf
def t31 : Tree := .fork .leaf t30
def t32 : Tree := .stem t31
def t33 : Tree := .fork t32 t18
def t34 : Tree := .fork t10 t33
def t35 : Tree := .fork .leaf t34
def t36 : Tree := .fork t9 t35
def t37 : Tree := .fork t36 .leaf
def t38 : Tree := .fork .leaf t37
def t39 : Tree := .stem t38
def t40 : Tree := .fork t39 t12
def t41 : Tree := .fork t10 t40
def t42 : Tree := .stem t1
def t43 : Tree := .fork t42 .leaf
def t44 : Tree := .stem t43
def t45 : Tree := .fork t44 .leaf
def t46 : Tree := .fork t9 t45
def t47 : Tree := .fork .leaf t46
def t48 : Tree := .stem t47
def t49 : Tree := .stem t9
def t50 : Tree := .fork .leaf t49
def t51 : Tree := .stem t50
def t52 : Tree := .fork t49 .leaf
def t53 : Tree := .fork .leaf t52
def t54 : Tree := .stem t53
def t55 : Tree := .fork t54 t1
def t56 : Tree := .fork .leaf t55
def t57 : Tree := .stem t56
def t58 : Tree := .fork .leaf t1
def t59 : Tree := .stem t58
def t60 : Tree := .fork t59 t52
def t61 : Tree := .fork t54 t60
def t62 : Tree := .stem t61
def t63 : Tree := .fork t62 t58
def t64 : Tree := .fork .leaf t63
def t65 : Tree := .stem t64
def t66 : Tree := .stem t49
def t67 : Tree := .fork .leaf t66
def t68 : Tree := .stem t67
def t69 : Tree := .fork t68 .leaf
def t70 : Tree := .fork t57 t69
def t71 : Tree := .stem t70
def t72 : Tree := .fork t71 t58
def t73 : Tree := .fork t65 t72
def t74 : Tree := .stem t73
def t75 : Tree := .fork t74 t9
def t76 : Tree := .stem t75
def t77 : Tree := .fork .leaf t43
def t78 : Tree := .fork t76 t77
def t79 : Tree := .fork t57 t78
def t80 : Tree := .stem t79
def t81 : Tree := .fork .leaf t41
def t82 : Tree := .fork t80 t81
def t83 : Tree := .fork t51 t82
def t84 : Tree := .fork .leaf t83
def t85 : Tree := .stem t84
def t86 : Tree := .stem t48
def t87 : Tree := .fork t85 t86
def t88 : Tree := .stem t87
def t89 : Tree := .fork t48 t88
def t90 : Tree := .fork t32 t12
def t91 : Tree := .fork t10 t90
def t92 : Tree := .fork .leaf t91
def t93 : Tree := .fork t9 t92
def t94 : Tree := .fork t93 .leaf
def t95 : Tree := .fork .leaf t94
def t96 : Tree := .stem t95
def t97 : Tree := .fork t96 t12
def t98 : Tree := .fork t10 t97
def t99 : Tree := .fork .leaf t98
def t100 : Tree := .fork t9 t99
def t101 : Tree := .fork t100 .leaf
def t102 : Tree := .fork .leaf t101
def t103 : Tree := .stem t102
def t104 : Tree := .fork t103 t18
def t105 : Tree := .fork t10 t104
def t106 : Tree := .fork .leaf t105
def t107 : Tree := .fork t9 t106
def t108 : Tree := .fork t107 .leaf
def t109 : Tree := .fork .leaf t108
def t110 : Tree := .stem t109
def t111 : Tree := .fork t110 t18
def t112 : Tree := .fork t10 t111
def t113 : Tree := .fork .leaf t3
def t114 : Tree := .fork .leaf t113
def t115 : Tree := .fork t1 t114
def t116 : Tree := .fork t1 t115
def t117 : Tree := .fork t9 .leaf
def t118 : Tree := .fork t44 t43
def t119 : Tree := .fork .leaf t118
def t120 : Tree := .fork t118 t119
def t121 : Tree := .fork .leaf t119
def t122 : Tree := .fork t120 t121
def t123 : Tree := .fork t122 t121
def t124 : Tree := .fork .leaf t121
def t125 : Tree := .fork t123 t124
def t126 : Tree := .fork t122 t125
def t127 : Tree := .fork t126 t124
def t128 : Tree := .fork t120 t127
def t129 : Tree := .fork t128 t121
def t130 : Tree := .fork t129 t124
def t131 : Tree := .fork t128 t130
def t132 : Tree := .fork t131 t124
def t133 : Tree := .fork t120 t132
def t134 : Tree := .fork t133 t121
def t135 : Tree := .fork t134 t124
def t136 : Tree := .fork t133 t135
def t137 : Tree := .fork t136 t124
def t138 : Tree := .fork t120 t137
def t139 : Tree := .fork t138 t121
def t140 : Tree := .fork t139 t124
def t141 : Tree := .fork t138 t140
def t142 : Tree := .fork t141 t124
def t143 : Tree := .fork t120 t142
def t144 : Tree := .fork t77 t119
def t145 : Tree := .fork t144 t132
def t146 : Tree := .fork t145 t121
def t147 : Tree := .fork t146 t124
def t148 : Tree := .fork t133 t147
def t149 : Tree := .fork t148 t124
def t150 : Tree := .fork t120 t149
def t151 : Tree := .fork t150 t140
def t152 : Tree := .fork t151 t124
def t153 : Tree := .fork t120 t152
def t154 : Tree := .fork t153 t121
def t155 : Tree := .fork t154 t124
def t156 : Tree := .fork t143 t155
def t157 : Tree := .fork t156 t124
def t158 : Tree := .fork t120 t157
def t159 : Tree := .fork t150 t121
def t160 : Tree := .fork t159 t124
def t161 : Tree := .fork t138 t160
def t162 : Tree := .fork t161 t124
def t163 : Tree := .fork t120 t162
def t164 : Tree := .fork t143 t121
def t165 : Tree := .fork t164 t124
def t166 : Tree := .fork t163 t165
def t167 : Tree := .fork t166 t124
def t168 : Tree := .fork t120 t167
def t169 : Tree := .fork t168 t121
def t170 : Tree := .fork t169 t124
def t171 : Tree := .fork t158 t170
def t172 : Tree := .fork t171 t124
def t173 : Tree := .fork t120 t172
def t174 : Tree := .fork t65 t173
def t175 : Tree := .fork t117 t174
def t176 : Tree := .stem t175
def t177 : Tree := .stem t176
def t178 : Tree := .fork .leaf t177
def t179 : Tree := .stem t178
def t180 : Tree := .fork t179 t1
def t181 : Tree := .fork .leaf t180
def t182 : Tree := .fork t176 t181

/-- `newline.dag` -/
def newline : Tree := t5

/-- `carriageReturn.dag` -/
def carriageReturn : Tree := t8

/-- `eqConstNewline.dag` -/
def eqConstNewline : Tree := t41

/-- `skipLine.dag` -/
def skipLine : Tree := t89

/-- `isHash.dag` -/
def isHash : Tree := t112

/-- `hash.dag` -/
def hash : Tree := t116

/-- `skipComment.dag` -/
def skipComment : Tree := t182

end TreeCalculus.Jets
