-- Generated by dag2lean.mjs; do not edit.
import TreeCalculus.Tree

namespace TreeCalculus.Jets
open TreeCalculus

def t1 : Tree := .stem .leaf
def t2 : Tree := .fork t1 .leaf
def t3 : Tree := .fork t1 t2
def t4 : Tree := .fork .leaf t3
def t5 : Tree := .fork t1 t4
def t6 : Tree := .fork .leaf .leaf
def t7 : Tree := .fork .leaf t6
def t8 : Tree := .fork t1 t6
def t9 : Tree := .fork t8 t7
def t10 : Tree := .fork .leaf t9
def t11 : Tree := .fork t6 t10
def t12 : Tree := .fork t11 .leaf
def t13 : Tree := .fork .leaf t12
def t14 : Tree := .stem t13
def t15 : Tree := .fork t10 t7
def t16 : Tree := .fork t14 t15
def t17 : Tree := .fork t7 t16
def t18 : Tree := .fork .leaf t17
def t19 : Tree := .fork t6 t18
def t20 : Tree := .fork t19 .leaf
def t21 : Tree := .fork .leaf t20
def t22 : Tree := .stem t21
def t23 : Tree := .fork t22 t9
def t24 : Tree := .fork t7 t23
def t25 : Tree := .fork .leaf t24
def t26 : Tree := .fork t6 t25
def t27 : Tree := .fork t26 .leaf
def t28 : Tree := .fork .leaf t27
def t29 : Tree := .stem t28
def t30 : Tree := .fork t29 t15
def t31 : Tree := .fork t7 t30
def t32 : Tree := .fork .leaf t31
def t33 : Tree := .fork t6 t32
def t34 : Tree := .fork t33 .leaf
def t35 : Tree := .fork .leaf t34
def t36 : Tree := .stem t35
def t37 : Tree := .fork t36 t9
def t38 : Tree := .fork t7 t37
def t39 : Tree := .fork .leaf t2
def t40 : Tree := .fork .leaf t39
def t41 : Tree := .fork .leaf t40
def t42 : Tree := .fork t1 t41
def t43 : Tree := .fork t1 t42
def t44 : Tree := .fork t29 t9
def t45 : Tree := .fork t7 t44
def t46 : Tree := .fork .leaf t45
def t47 : Tree := .fork t6 t46
def t48 : Tree := .fork t47 .leaf
def t49 : Tree := .fork .leaf t48
def t50 : Tree := .stem t49
def t51 : Tree := .fork t50 t9
def t52 : Tree := .fork t7 t51
def t53 : Tree := .fork .leaf t52
def t54 : Tree := .fork t6 t53
def t55 : Tree := .fork t54 .leaf
def t56 : Tree := .fork .leaf t55
def t57 : Tree := .stem t56
def t58 : Tree := .fork t57 t15
def t59 : Tree := .fork t7 t58
def t60 : Tree := .fork .leaf t59
def t61 : Tree := .fork t6 t60
def t62 : Tree := .fork t61 .leaf
def t63 : Tree := .fork .leaf t62
def t64 : Tree := .stem t63
def t65 : Tree := .fork t64 t15
def t66 : Tree := .fork t7 t65
def t67 : Tree := .stem t1
def t68 : Tree := .fork t67 .leaf
def t69 : Tree := .fork .leaf t1
def t70 : Tree := .fork .leaf t69
def t71 : Tree := .fork .leaf t70
def t72 : Tree := .fork t68 t71
def t73 : Tree := .fork t72 .leaf
def t74 : Tree := .fork .leaf t73
def t75 : Tree := .stem t74
def t76 : Tree := .fork t75 t38
def t77 : Tree := .stem t76
def t78 : Tree := .fork t22 t15
def t79 : Tree := .fork t7 t78
def t80 : Tree := .fork .leaf t79
def t81 : Tree := .fork t6 t80
def t82 : Tree := .fork t81 .leaf
def t83 : Tree := .fork .leaf t82
def t84 : Tree := .stem t83
def t85 : Tree := .fork t84 t9
def t86 : Tree := .fork t7 t85
def t87 : Tree := .fork .leaf t86
def t88 : Tree := .fork t6 t87
def t89 : Tree := .fork t88 .leaf
def t90 : Tree := .fork .leaf t89
def t91 : Tree := .stem t90
def t92 : Tree := .fork t91 t15
def t93 : Tree := .fork t7 t92
def t94 : Tree := .fork .leaf t93
def t95 : Tree := .fork t77 t94
def t96 : Tree := .stem t95
def t97 : Tree := .fork t96 t68
def t98 : Tree := .fork t1 t39
def t99 : Tree := .fork .leaf t98
def t100 : Tree := .fork t6 .leaf
def t101 : Tree := .stem t6
def t102 : Tree := .fork t101 .leaf
def t103 : Tree := .fork .leaf t102
def t104 : Tree := .stem t103
def t105 : Tree := .stem t69
def t106 : Tree := .fork t105 t102
def t107 : Tree := .fork t104 t106
def t108 : Tree := .stem t107
def t109 : Tree := .fork t108 t69
def t110 : Tree := .fork .leaf t109
def t111 : Tree := .stem t110
def t112 : Tree := .stem t68
def t113 : Tree := .fork t112 t68
def t114 : Tree := .fork .leaf t113
def t115 : Tree := .fork t113 t114
def t116 : Tree := .fork .leaf t114
def t117 : Tree := .fork t115 t116
def t118 : Tree := .fork t117 t116
def t119 : Tree := .fork .leaf t116
def t120 : Tree := .fork t118 t119
def t121 : Tree := .fork t117 t120
def t122 : Tree := .fork t121 t119
def t123 : Tree := .fork t115 t122
def t124 : Tree := .fork t123 t116
def t125 : Tree := .fork t124 t119
def t126 : Tree := .fork t123 t125
def t127 : Tree := .fork t126 t119
def t128 : Tree := .fork t115 t127
def t129 : Tree := .fork t128 t116
def t130 : Tree := .fork t129 t119
def t131 : Tree := .fork t128 t130
def t132 : Tree := .fork t131 t119
def t133 : Tree := .fork t115 t132
def t134 : Tree := .fork t133 t116
def t135 : Tree := .fork t134 t119
def t136 : Tree := .fork t133 t135
def t137 : Tree := .fork t136 t119
def t138 : Tree := .fork t115 t137
def t139 : Tree := .fork .leaf t68
def t140 : Tree := .fork t139 t114
def t141 : Tree := .fork t140 t127
def t142 : Tree := .fork t141 t116
def t143 : Tree := .fork t142 t119
def t144 : Tree := .fork t128 t143
def t145 : Tree := .fork t144 t119
def t146 : Tree := .fork t115 t145
def t147 : Tree := .fork t146 t135
def t148 : Tree := .fork t147 t119
def t149 : Tree := .fork t115 t148
def t150 : Tree := .fork t149 t116
def t151 : Tree := .fork t150 t119
def t152 : Tree := .fork t138 t151
def t153 : Tree := .fork t152 t119
def t154 : Tree := .fork t115 t153
def t155 : Tree := .fork t146 t116
def t156 : Tree := .fork t155 t119
def t157 : Tree := .fork t133 t156
def t158 : Tree := .fork t157 t119
def t159 : Tree := .fork t115 t158
def t160 : Tree := .fork t138 t116
def t161 : Tree := .fork t160 t119
def t162 : Tree := .fork t159 t161
def t163 : Tree := .fork t162 t119
def t164 : Tree := .fork t115 t163
def t165 : Tree := .fork t164 t116
def t166 : Tree := .fork t165 t119
def t167 : Tree := .fork t154 t166
def t168 : Tree := .fork t167 t119
def t169 : Tree := .fork t115 t168
def t170 : Tree := .fork t111 t169
def t171 : Tree := .fork t100 t170
def t172 : Tree := .stem t171
def t173 : Tree := .stem t172
def t174 : Tree := .fork .leaf t173
def t175 : Tree := .stem t174
def t176 : Tree := .fork t175 t1
def t177 : Tree := .fork .leaf t176
def t178 : Tree := .fork t172 t177
def t179 : Tree := .fork .leaf t139
def t180 : Tree := .fork t113 t179
def t181 : Tree := .fork t180 .leaf
def t182 : Tree := .fork .leaf t181
def t183 : Tree := .stem t182
def t184 : Tree := .fork t183 t38
def t185 : Tree := .stem t184
def t186 : Tree := .fork .leaf t101
def t187 : Tree := .stem t186
def t188 : Tree := .stem t185
def t189 : Tree := .fork .leaf t188
def t190 : Tree := .stem t189
def t191 : Tree := .fork t190 t1
def t192 : Tree := .fork t187 t191
def t193 : Tree := .fork .leaf t192
def t194 : Tree := .fork t185 t193
def t195 : Tree := .fork t6 t194
def t196 : Tree := .fork t112 .leaf
def t197 : Tree := .fork t6 t196
def t198 : Tree := .fork .leaf t197
def t199 : Tree := .stem t198
def t200 : Tree := .fork t104 t1
def t201 : Tree := .fork .leaf t200
def t202 : Tree := .stem t201
def t203 : Tree := .stem t101
def t204 : Tree := .fork .leaf t203
def t205 : Tree := .stem t204
def t206 : Tree := .fork t205 .leaf
def t207 : Tree := .fork t202 t206
def t208 : Tree := .stem t207
def t209 : Tree := .fork t208 t69
def t210 : Tree := .fork t111 t209
def t211 : Tree := .stem t210
def t212 : Tree := .fork t211 t6
def t213 : Tree := .stem t212
def t214 : Tree := .fork t213 t139
def t215 : Tree := .fork t202 t214
def t216 : Tree := .stem t215
def t217 : Tree := .fork .leaf t38
def t218 : Tree := .fork t216 t217
def t219 : Tree := .fork t187 t218
def t220 : Tree := .fork .leaf t219
def t221 : Tree := .stem t220
def t222 : Tree := .stem t199
def t223 : Tree := .fork t221 t222
def t224 : Tree := .stem t223
def t225 : Tree := .fork t199 t224

/-- `carriageReturn.dag` -/
def carriageReturn : Tree := t5

/-- `eqConstNewline.dag` -/
def eqConstNewline : Tree := t38

/-- `hash.dag` -/
def hash : Tree := t43

/-- `isHash.dag` -/
def isHash : Tree := t66

/-- `isNewline.dag` -/
def isNewline : Tree := t97

/-- `newline.dag` -/
def newline : Tree := t99

/-- `skipComment.dag` -/
def skipComment : Tree := t178

/-- `skipLine.dag` -/
def skipLine : Tree := t195

/-- `skipLineFix.dag` -/
def skipLineFix : Tree := t225

end TreeCalculus.Jets
