-- Generated by dag2lean.mjs; do not edit.
import TreeCalculus.Tree

namespace TreeCalculus.Jets
open TreeCalculus

def t1 : Tree := .stem .leaf
def t2 : Tree := .fork t1 .leaf
def t3 : Tree := .fork .leaf t2
def t4 : Tree := .fork t1 t3
def t5 : Tree := .fork .leaf t4
def t6 : Tree := .fork t1 t2
def t7 : Tree := .fork .leaf t6
def t8 : Tree := .fork t1 t7
def t9 : Tree := .fork .leaf .leaf
def t10 : Tree := .fork .leaf t9
def t11 : Tree := .fork t1 t9
def t12 : Tree := .fork t11 t10
def t13 : Tree := .fork .leaf t12
def t14 : Tree := .fork t9 t13
def t15 : Tree := .fork t14 .leaf
def t16 : Tree := .fork .leaf t15
def t17 : Tree := .stem t16
def t18 : Tree := .fork t13 t10
def t19 : Tree := .fork t17 t18
def t20 : Tree := .fork t10 t19
def t21 : Tree := .fork .leaf t20
def t22 : Tree := .fork t9 t21
def t23 : Tree := .fork t22 .leaf
def t24 : Tree := .fork .leaf t23
def t25 : Tree := .stem t24
def t26 : Tree := .fork t25 t12
def t27 : Tree := .fork t10 t26
def t28 : Tree := .fork .leaf t27
def t29 : Tree := .fork t9 t28
def t30 : Tree := .fork t29 .leaf
def t31 : Tree := .fork .leaf t30
def t32 : Tree := .stem t31
def t33 : Tree := .fork t32 t18
def t34 : Tree := .fork t10 t33
def t35 : Tree := .fork .leaf t34
def t36 : Tree := .fork t9 t35
def t37 : Tree := .fork t36 .leaf
def t38 : Tree := .fork .leaf t37
def t39 : Tree := .stem t38
def t40 : Tree := .fork t39 t12
def t41 : Tree := .fork t10 t40
def t42 : Tree := .stem t1
def t43 : Tree := .fork t42 .leaf
def t44 : Tree := .stem t43
def t45 : Tree := .fork t44 .leaf
def t46 : Tree := .fork t9 t45
def t47 : Tree := .fork .leaf t46
def t48 : Tree := .stem t47
def t49 : Tree := .stem t9
def t50 : Tree := .fork .leaf t49
def t51 : Tree := .stem t50
def t52 : Tree := .fork t49 .leaf
def t53 : Tree := .fork .leaf t52
def t54 : Tree := .stem t53
def t55 : Tree := .fork t54 t1
def t56 : Tree := .fork .leaf t55
def t57 : Tree := .stem t56
def t58 : Tree := .fork .leaf t1
def t59 : Tree := .stem t58
def t60 : Tree := .fork t59 t52
def t61 : Tree := .fork t54 t60
def t62 : Tree := .stem t61
def t63 : Tree := .fork t62 t58
def t64 : Tree := .fork .leaf t63
def t65 : Tree := .stem t64
def t66 : Tree := .stem t49
def t67 : Tree := .fork .leaf t66
def t68 : Tree := .stem t67
def t69 : Tree := .fork t68 .leaf
def t70 : Tree := .fork t57 t69
def t71 : Tree := .stem t70
def t72 : Tree := .fork t71 t58
def t73 : Tree := .fork t65 t72
def t74 : Tree := .stem t73
def t75 : Tree := .fork t74 t9
def t76 : Tree := .stem t75
def t77 : Tree := .fork .leaf t43
def t78 : Tree := .fork t76 t77
def t79 : Tree := .fork t57 t78
def t80 : Tree := .stem t79
def t81 : Tree := .fork .leaf t41
def t82 : Tree := .fork t80 t81
def t83 : Tree := .fork t51 t82
def t84 : Tree := .fork .leaf t83
def t85 : Tree := .stem t84
def t86 : Tree := .stem t48
def t87 : Tree := .fork t85 t86
def t88 : Tree := .stem t87
def t89 : Tree := .fork t48 t88
def t90 : Tree := .fork t32 t12
def t91 : Tree := .fork t10 t90
def t92 : Tree := .fork .leaf t91
def t93 : Tree := .fork t9 t92
def t94 : Tree := .fork t93 .leaf
def t95 : Tree := .fork .leaf t94
def t96 : Tree := .stem t95
def t97 : Tree := .fork t96 t12
def t98 : Tree := .fork t10 t97
def t99 : Tree := .fork .leaf t98
def t100 : Tree := .fork t9 t99
def t101 : Tree := .fork t100 .leaf
def t102 : Tree := .fork .leaf t101
def t103 : Tree := .stem t102
def t104 : Tree := .fork t103 t18
def t105 : Tree := .fork t10 t104
def t106 : Tree := .fork .leaf t105
def t107 : Tree := .fork t9 t106
def t108 : Tree := .fork t107 .leaf
def t109 : Tree := .fork .leaf t108
def t110 : Tree := .stem t109
def t111 : Tree := .fork t110 t18
def t112 : Tree := .fork t10 t111
def t113 : Tree := .fork .leaf t58
def t114 : Tree := .fork .leaf t113
def t115 : Tree := .fork t43 t114
def t116 : Tree := .fork t115 .leaf
def t117 : Tree := .fork .leaf t116
def t118 : Tree := .stem t117
def t119 : Tree := .fork t118 t41
def t120 : Tree := .stem t119
def t121 : Tree := .fork t25 t18
def t122 : Tree := .fork t10 t121
def t123 : Tree := .fork .leaf t122
def t124 : Tree := .fork t9 t123
def t125 : Tree := .fork t124 .leaf
def t126 : Tree := .fork .leaf t125
def t127 : Tree := .stem t126
def t128 : Tree := .fork t127 t12
def t129 : Tree := .fork t10 t128
def t130 : Tree := .fork .leaf t129
def t131 : Tree := .fork t9 t130
def t132 : Tree := .fork t131 .leaf
def t133 : Tree := .fork .leaf t132
def t134 : Tree := .stem t133
def t135 : Tree := .fork t134 t18
def t136 : Tree := .fork t10 t135
def t137 : Tree := .fork .leaf t136
def t138 : Tree := .fork t120 t137
def t139 : Tree := .stem t138
def t140 : Tree := .fork t139 t43
def t141 : Tree := .fork .leaf t3
def t142 : Tree := .fork .leaf t141
def t143 : Tree := .fork t1 t142
def t144 : Tree := .fork t1 t143
def t145 : Tree := .fork t9 .leaf
def t146 : Tree := .fork t44 t43
def t147 : Tree := .fork .leaf t146
def t148 : Tree := .fork t146 t147
def t149 : Tree := .fork .leaf t147
def t150 : Tree := .fork t148 t149
def t151 : Tree := .fork t150 t149
def t152 : Tree := .fork .leaf t149
def t153 : Tree := .fork t151 t152
def t154 : Tree := .fork t150 t153
def t155 : Tree := .fork t154 t152
def t156 : Tree := .fork t148 t155
def t157 : Tree := .fork t156 t149
def t158 : Tree := .fork t157 t152
def t159 : Tree := .fork t156 t158
def t160 : Tree := .fork t159 t152
def t161 : Tree := .fork t148 t160
def t162 : Tree := .fork t161 t149
def t163 : Tree := .fork t162 t152
def t164 : Tree := .fork t161 t163
def t165 : Tree := .fork t164 t152
def t166 : Tree := .fork t148 t165
def t167 : Tree := .fork t166 t149
def t168 : Tree := .fork t167 t152
def t169 : Tree := .fork t166 t168
def t170 : Tree := .fork t169 t152
def t171 : Tree := .fork t148 t170
def t172 : Tree := .fork t77 t147
def t173 : Tree := .fork t172 t160
def t174 : Tree := .fork t173 t149
def t175 : Tree := .fork t174 t152
def t176 : Tree := .fork t161 t175
def t177 : Tree := .fork t176 t152
def t178 : Tree := .fork t148 t177
def t179 : Tree := .fork t178 t168
def t180 : Tree := .fork t179 t152
def t181 : Tree := .fork t148 t180
def t182 : Tree := .fork t181 t149
def t183 : Tree := .fork t182 t152
def t184 : Tree := .fork t171 t183
def t185 : Tree := .fork t184 t152
def t186 : Tree := .fork t148 t185
def t187 : Tree := .fork t178 t149
def t188 : Tree := .fork t187 t152
def t189 : Tree := .fork t166 t188
def t190 : Tree := .fork t189 t152
def t191 : Tree := .fork t148 t190
def t192 : Tree := .fork t171 t149
def t193 : Tree := .fork t192 t152
def t194 : Tree := .fork t191 t193
def t195 : Tree := .fork t194 t152
def t196 : Tree := .fork t148 t195
def t197 : Tree := .fork t196 t149
def t198 : Tree := .fork t197 t152
def t199 : Tree := .fork t186 t198
def t200 : Tree := .fork t199 t152
def t201 : Tree := .fork t148 t200
def t202 : Tree := .fork t65 t201
def t203 : Tree := .fork t145 t202
def t204 : Tree := .stem t203
def t205 : Tree := .stem t204
def t206 : Tree := .fork .leaf t205
def t207 : Tree := .stem t206
def t208 : Tree := .fork t207 t1
def t209 : Tree := .fork .leaf t208
def t210 : Tree := .fork t204 t209
def t211 : Tree := .fork .leaf t77
def t212 : Tree := .fork t146 t211
def t213 : Tree := .fork t212 .leaf
def t214 : Tree := .fork .leaf t213
def t215 : Tree := .stem t214
def t216 : Tree := .fork t215 t41
def t217 : Tree := .stem t216
def t218 : Tree := .stem t217
def t219 : Tree := .fork .leaf t218
def t220 : Tree := .stem t219
def t221 : Tree := .fork t220 t1
def t222 : Tree := .fork t51 t221
def t223 : Tree := .fork .leaf t222
def t224 : Tree := .fork t217 t223
def t225 : Tree := .fork t9 t224

/-- `newline.dag` -/
def newline : Tree := t5

/-- `carriageReturn.dag` -/
def carriageReturn : Tree := t8

/-- `eqConstNewline.dag` -/
def eqConstNewline : Tree := t41

/-- `skipLineFix.dag` -/
def skipLineFix : Tree := t89

/-- `isHash.dag` -/
def isHash : Tree := t112

/-- `isNewline.dag` -/
def isNewline : Tree := t140

/-- `hash.dag` -/
def hash : Tree := t144

/-- `skipComment.dag` -/
def skipComment : Tree := t210

/-- `skipLine.dag` -/
def skipLine : Tree := t225

end TreeCalculus.Jets
