import Rules.Core
import Rules.KernelRfl
import TreeCalculus.Progress

/-!
# Rules derived from the library's trees

`Rules/Core.lean` is generated by `Rules/gen-rules.mjs` (its second line is the command) from
`Rules/trees/core.dag`: lambada's `compiler/prelude.dag` followed by `bin/dag.js extract` of the
functions named there from arboretum's built `src/.dag-bundle-canonical`. For each function: one
rule per argument it is applied to, one for its whole application, and a `RuleTree` where it
triages an argument — each checked by `decide +kernel` (`TreeCalculus/RuleJets.lean`). Among them:

* `fix_1`: `fix f` ⟶ the value `△ U (△ (△ (△ (△ △ f)) K2))`, in 26 transitions;
* `fix_2`: `fix f x` ⟶ `f (fix f) x`, in 21, reusing the matched `fix f` (no allocation);
* `let_app`: `let x f` ⟶ `f x`, in 17; `wait_app`: `wait a b c` ⟶ `a b c`, in 77;
* `p_c_1`, `p_c_2`: `:c f`, `:c f g` ⟶ their closures, in 26 and 6; `p_c_app`: `:c f g x` ⟶ `f x g`.
-/

namespace Rules

open TreeCalculus Term Core

/-- `runtime_sound` for a runtime that fires any rule of `Core`. -/
theorem core_runtime_sound (hm : m.Sound)
    (h : Star (RStep (RuleJet ((all.flatMap (·.rules)).map (·.1)))) ⟨.reduce a b [], [], m⟩
      ⟨.dispatch r [], [], m'⟩) :
    Apply a.toTerm b.toTerm r.toTerm ∧ m'.Sound :=
  rules_runtime_sound (checkRules_sound (Checked.ok_all all)) hm h

/-- What a runtime may do with `fix`: build `fix f` without looking at `f`, and answer `fix f x`
by going straight to `f (fix f) x`. -/
theorem fix_runtime_sound (hm : m.Sound)
    (h : Star (RStep (RuleJet [fix_1, fix_2])) ⟨.reduce a b [], [], m⟩ ⟨.dispatch r [], [], m'⟩) :
    Apply a.toTerm b.toTerm r.toTerm ∧ m'.Sound :=
  rules_runtime_sound (by
    simp only [List.forall_mem_cons, List.not_mem_nil, false_imp_iff, implies_true, and_true]
    exact ⟨checkRule_sound fix_1_check, checkRule_sound fix_2_check⟩) hm h

/-- The fix rules take a step on every instance: under any policy that idles finitely, a runtime
firing them returns `r` iff the machine does (`TreeCalculus/Progress.lean`). -/
theorem fix_plus : RuleJet [fix_1, fix_2] s t → Plus s t :=
  RuleJet.plus fun ρ hρ σ => by
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hρ
    rcases hρ with rfl | rfl
    · exact checkRule_plus fix_1_check σ
    · exact checkRule_plus fix_2_check σ

theorem fix_memoPolicy_returns_iff (hm : m.Sound) :
    (∃ m', Star (MemoPolicy (RuleJet [fix_1, fix_2])) (RState.init a b m)
      ⟨.dispatch r [], [], m'⟩) ↔ Run a b r :=
  memoPolicy_returns_iff (fun _ _ => fix_plus) hm

/-- The same check as a kernel defeq (`Rules/KernelRfl.lean`): what `gen-rules.mjs --rfl` emits,
cheaper where a rule's right side holds big `lit`s. -/
example : checkRule fix_2 21 = true := decide_eq_true (by kernel_rfl)

/-- A rule checked on a general pattern holds, with its length, on every special one: `fix K x`. -/
example : checkRule (fix_2.inst 0 (.lit p_kV)) 21 = true := checkRule_inst fix_2_check 0 _

/-- No rule of `Core` is longer than 105 transitions, so a run firing them takes at least `N / 105`
transitions where the machine takes `N`. -/
theorem core_length_bound (hN : steps N (.reduce a b []) = some (.dispatch v []))
    (h : StarN (fun s t => step s = some t ∨ RuleJet ((all.flatMap (·.rules)).map (·.1)) s t) M
      (.reduce a b []) (.dispatch r [])) :
    N ≤ M * 105 :=
  rules_length_bound (Checked.ok_all all) (by decide) (by decide +kernel) hN h

end Rules
