-- Generated by dag2lean.mjs; do not edit.
import TreeCalculus.Value

namespace Cpp.Jets
open TreeCalculus

def t1 : Value := .stem .leaf
def t2 : Value := .fork t1 .leaf
def t3 : Value := .fork .leaf t2
def t4 : Value := .fork t1 t3
def t5 : Value := .fork .leaf t4
def t6 : Value := .fork .leaf .leaf
def t7 : Value := .stem t1
def t8 : Value := .fork t7 .leaf
def t9 : Value := .stem t8
def t10 : Value := .fork t9 t8
def t11 : Value := .fork .leaf t8
def t12 : Value := .fork .leaf t11
def t13 : Value := .fork t10 t12
def t14 : Value := .fork t13 .leaf
def t15 : Value := .fork .leaf t14
def t16 : Value := .stem t15
def t17 : Value := .fork .leaf t6
def t18 : Value := .fork t1 t6
def t19 : Value := .fork t18 t17
def t20 : Value := .fork .leaf t19
def t21 : Value := .fork t6 t20
def t22 : Value := .fork t21 .leaf
def t23 : Value := .fork .leaf t22
def t24 : Value := .stem t23
def t25 : Value := .fork t20 t17
def t26 : Value := .fork t24 t25
def t27 : Value := .fork t17 t26
def t28 : Value := .fork .leaf t27
def t29 : Value := .fork t6 t28
def t30 : Value := .fork t29 .leaf
def t31 : Value := .fork .leaf t30
def t32 : Value := .stem t31
def t33 : Value := .fork t32 t19
def t34 : Value := .fork t17 t33
def t35 : Value := .fork .leaf t34
def t36 : Value := .fork t6 t35
def t37 : Value := .fork t36 .leaf
def t38 : Value := .fork .leaf t37
def t39 : Value := .stem t38
def t40 : Value := .fork t39 t25
def t41 : Value := .fork t17 t40
def t42 : Value := .fork .leaf t41
def t43 : Value := .fork t6 t42
def t44 : Value := .fork t43 .leaf
def t45 : Value := .fork .leaf t44
def t46 : Value := .stem t45
def t47 : Value := .fork t46 t19
def t48 : Value := .fork t17 t47
def t49 : Value := .fork t16 t48
def t50 : Value := .stem t49
def t51 : Value := .stem t6
def t52 : Value := .fork .leaf t51
def t53 : Value := .stem t52
def t54 : Value := .stem t50
def t55 : Value := .fork .leaf t54
def t56 : Value := .stem t55
def t57 : Value := .fork t56 t1
def t58 : Value := .fork t53 t57
def t59 : Value := .fork .leaf t58
def t60 : Value := .fork t50 t59
def t61 : Value := .fork t6 t60

/-- `newline.dag` -/
def newline : Value := t5

/-- `skipLine.dag` -/
def skipLine : Value := t61

end Cpp.Jets
