#!/usr/bin/env node
// The jets the runtime takes, from the one table below: each tree byte for byte as this
// directory holds it, in the header the eager evaluator interns them from, and each relation in
// a Lean file that type-checks only if the runtime takes nothing that is not proven.
//
//   node proofs/jets/embed.mjs          write both
//   node proofs/jets/embed.mjs --check  fail if either is not what it would write
//
// `implementation/cpp/dag-machine/test.sh` runs the check, so an embedding cannot fall behind
// the trees the theorems are about; `gen.mjs` runs this after writing them.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// `DropJet F [k]` (Check.lean), licensed by `<F>_check : checkDropThrough F [k] n = true`. Only
// the drop-through relation, and one separator: what ships (runner.md, "Jets").
const jets = [
  { tree: 'skipLine', through: 'newline' },
];

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const dag = (name) => readFileSync(join(here, `${name}.dag`), 'utf8');
const names = [...new Set(jets.flatMap(({ tree, through }) => [tree, through]))];

// apply() looks for a DropJet only where it meets a pair, which for a triage node △(△wx)y is
// the step every skip and hit starts from: so that is the shape its tree has to have. A node
// here is the array of its children; the lines of a value only ever add one.
const value = (name) => {
  const env = new Map([['△', []]]);
  let top;
  for (const w of dag(name).trim().split('\n').map((line) => line.split(' ')))
    if (w.length === 3) env.set(w[0], [...env.get(w[1]), env.get(w[2])]);
    else top = env.get(w[0]);
  return top;
};
for (const { tree } of jets)
  if (value(tree).length !== 2 || value(tree)[0].length !== 2)
    throw new Error(`${tree}: apply() takes a DropJet only on a triage node, △(△wx)y`);

const header = `// Generated by proofs/jets/embed.mjs; do not edit.
//
// The jets EagerGraphNilMmap32 takes: each tree as proofs/jets/<name>.dag holds it, the bytes
// Jets/Trees.lean is generated from too, and the relation it is taken under, proven in
// proofs/TreeCalculus/Jets/Runtime.lean (runtimeJets_sound).
#pragma once

namespace jets {

${names.map((name) => `inline constexpr char ${name}[] = R"dag(${dag(name)})dag";`).join('\n\n')}

// DropJet f [k]: f applied to a list drops it through the first element that is k.
struct DropThrough { const char *f, *k; };
inline constexpr DropThrough drop_through[] = {
${jets.map(({ tree, through }) => `  {${tree}, ${through}}, // ${tree}_check`).join('\n')}
};

} // namespace jets
`;

const relation = ({ tree, through }) => `DropJet ${tree} [${through}]`;
const reaches = ({ tree }) => `DropJet.reaches ${tree}_check`;
const proof = jets.slice(0, -1).reduceRight(
  (rest, jet) => `Or.elim h (${reaches(jet)}) fun h => ${rest}`, `${reaches(jets.at(-1))} h`);

const lean = `-- Generated by jets/embed.mjs; do not edit.
import TreeCalculus.Jets

namespace TreeCalculus.Jets

/-- The jets \`implementation/cpp/jets.hpp\` embeds, as the transitions the runtime takes. -/
def runtimeJets (s t : State Tree) : Prop :=
  ${jets.map((jet) => `${relation(jet)} s t`).join(' ∨\n  ')}

/-- The runtime, with its memo and exactly these jets, returns what the reduction rules say. -/
theorem runtimeJets_sound (hm : m.Sound)
    (h : Star (RStep runtimeJets) ⟨.reduce a b [], [], m⟩ ⟨.dispatch r [], [], m'⟩) :
    Run a b r ∧ m'.Sound :=
  runtime_sound (fun _ _ h => ${proof}) hm h

end TreeCalculus.Jets
`;

const outputs = {
  [join(root, 'implementation/cpp/jets.hpp')]: header,
  [join(here, '../TreeCalculus/Jets/Runtime.lean')]: lean,
};
const read = (path) => { try { return readFileSync(path, 'utf8'); } catch { return null; } };
const check = process.argv.includes('--check');
let stale = 0;
for (const [path, text] of Object.entries(outputs)) {
  if (!check) writeFileSync(path, text);
  else if (read(path) !== text) {
    console.error(`${relative(root, path)} is not what proofs/jets/embed.mjs writes; run it`);
    ++stale;
  }
}
process.exit(stale ? 1 : 0);
