// Emit Lean definitions (Value nodes, one def per distinct node, like Cpp/dag2lean.mjs) for the
// fix rule derived by sym.mjs: lhs `reduce P (var 1) []`, rhs its residual.
import * as T from './tc.mjs';
import * as S from './sym.mjs';
const env = T.loadBundle('/home/user/forest/src/.dag-bundle-arboretum-reduced');
const fix = env.get('fix');
const P = S.derive(S.reduce(S.lit(fix), S.svar(0))).s.r;
const rule = S.derive(S.reduce(P, S.svar(1)));
const names = new Map(); const defs = [];
function v(x) { // Value expression for node x
  if (T.isLeaf(x)) return '.leaf';
  if (names.has(x)) return names.get(x);
  const e = T.isStem(x) ? `.stem ${v(T.L[x])}` : `.fork ${v(T.L[x])} ${v(T.R[x])}`;
  const n = `fixT${names.size + 1}`; names.set(x, n); defs.push(`def ${n} : Value := ${e}`); return n;
}
function sv(p) {
  switch (p.t) {
    case 'lit': return `(.lit ${v(p.v)})`;
    case 'var': return `(.var ${p.i})`;
    case 'stem': return `(.stem ${sv(p.u)})`;
    case 'fork': return `(.fork ${sv(p.u)} ${sv(p.v)})`;
  }
}
const fr = (f) => f.t === 'applyTo' ? `.applyTo ${sv(f.arg)}` : `.computeAndApply ${sv(f.fn)} ${sv(f.arg)}`;
const st = (s) => s.t === 'reduce' ? `.reduce ${sv(s.a)} ${sv(s.b)} [${s.k.map(fr).join(', ')}]` : `.dispatch ${sv(s.r)} [${s.k.map(fr).join(', ')}]`;
const fixV = v(fix);
const pat = sv(P);
const rhs = st(rule.s);
console.log(`-- Generated by gen-lean.mjs from arboretum's \`fix\` (forest src/.dag-bundle-arboretum-reduced).
${defs.join('\n')}

/-- arboretum's \`fix\`. -/
def fixV : Value := ${fixV}
/-- \`fix f\`, as the value \`apply(fix, f)\` returns, \`f = var 0\` (it never inspects \`f\`). -/
def fixPat : SValue := ${pat}
/-- \`apply(fix f, x) ⟶ apply(apply(f, fix f), x)\`: ${rule.steps} reduce steps, ${rule.transitions} transitions. -/
def fixRule : Rule := ⟨.reduce fixPat (.var 1) [], ${rhs}⟩`);
// also the rule that builds \`fix f\`
const d1 = S.derive(S.reduce(S.lit(fix), S.svar(0)));
console.log(`/-- \`apply(fix, f)\` returns \`fix f\` without looking at \`f\`: ${d1.steps} reduce steps, ${d1.transitions} transitions. -/
def fixBuild : Rule := ⟨.reduce (.lit fixV) (.var 0) [], ${st(d1.s)}⟩`);
