-- Generated by gen-rules.mjs from Rules/trees/core.dag; do not edit.
--   node Rules/gen-rules.mjs --ns Rules.Core Rules/trees/core.dag fix/2 fix__wait/2 fix__naive/2 let/2 wait/3 :c/3 :b/3 :s/3 :k/2 :i/1 :ct/2 self_apply/1 triage/4/split Bool.match/3/split List.match/3/split Option.match/3/split Pair.match/2/split List.map/2/split List.length/1/split
import TreeCalculus.RuleJets

namespace Rules.Core
open TreeCalculus

noncomputable def t1 : Value := Value.stem Value.leaf
noncomputable def t2 : Value := Value.stem t1
noncomputable def t3 : Value := Value.fork t2 Value.leaf
noncomputable def t4 : Value := Value.stem t3
noncomputable def t5 : Value := Value.fork Value.leaf Value.leaf
noncomputable def t6 : Value := Value.stem (Value.fork Value.leaf (Value.fork t5 (Value.fork t4 Value.leaf)))
noncomputable def t7 : Value := Value.stem t6
noncomputable def t8 : Value := Value.fork Value.leaf t7
noncomputable def t9 : Value := Value.stem t5
noncomputable def t10 : Value := Value.fork t9 Value.leaf
noncomputable def t11 : Value := Value.stem (Value.fork Value.leaf t10)
noncomputable def t12 : Value := Value.fork t11 t1
noncomputable def t13 : Value := Value.stem t12
noncomputable def t14 : Value := Value.fork (Value.stem t8) (Value.fork t9 (Value.fork t13 t8))
noncomputable def t15 : Value := Value.stem (Value.fork (Value.stem (Value.fork Value.leaf (Value.stem (Value.stem (Value.fork t4 t1))))) t1)
noncomputable def t16 : Value := Value.stem t15
noncomputable def t17 : Value := Value.fork Value.leaf t16
noncomputable def t18 : Value := Value.fork (Value.stem (Value.fork Value.leaf (Value.fork (Value.stem t17) t1))) (Value.fork t13 t17)
noncomputable def t19 : Value := Value.fork t4 t3
noncomputable def t20 : Value := Value.stem (Value.fork (Value.stem (Value.fork Value.leaf (Value.stem (Value.stem t19)))) t1)
noncomputable def t21 : Value := Value.fork (Value.stem (Value.fork Value.leaf (Value.stem t20))) t1
noncomputable def t22 : Value := Value.fork Value.leaf t21
noncomputable def t23 : Value := Value.fork (Value.stem t22) (Value.fork t13 t22)
noncomputable def t24 : Value := Value.fork (Value.stem (Value.fork Value.leaf (Value.stem t4))) t1
noncomputable def t25 : Value := Value.fork Value.leaf t1
noncomputable def t26 : Value := Value.fork Value.leaf t12
noncomputable def t27 : Value := Value.stem t26
noncomputable def t28 : Value := Value.stem t25
noncomputable def t29 : Value := Value.fork (Value.stem (Value.fork t11 (Value.fork t28 t10))) t25
noncomputable def t30 : Value := Value.stem (Value.fork Value.leaf t29)
noncomputable def t31 : Value := Value.fork t30 (Value.fork (Value.stem (Value.fork t27 t10)) t25)
noncomputable def t32 : Value := Value.stem t9
noncomputable def t33 : Value := Value.fork (Value.stem (Value.fork Value.leaf t32)) Value.leaf
noncomputable def t34 : Value := Value.fork (Value.stem (Value.fork t30 (Value.fork (Value.stem (Value.fork t27 t33)) t25))) t5
noncomputable def t35 : Value := Value.fork (Value.stem t33) t5
noncomputable def t36 : Value := Value.fork (Value.stem (Value.fork t30 t33)) t5
noncomputable def t37 : Value := Value.stem (Value.fork Value.leaf t9)
noncomputable def t38 : Value := Value.fork (Value.stem (Value.fork Value.leaf t14)) (Value.fork (Value.stem (Value.fork Value.leaf (Value.stem t37))) (Value.fork t30 (Value.fork (Value.stem (Value.fork Value.leaf (Value.stem t27))) t32)))
noncomputable def t39 : Value := Value.stem (Value.fork (Value.fork (Value.fork Value.leaf t2) (Value.fork Value.leaf (Value.fork (Value.stem (Value.fork Value.leaf (Value.stem t28))) t19))) Value.leaf)
noncomputable def t40 : Value := Value.fork (Value.fork t1 Value.leaf) Value.leaf
noncomputable def t41 : Value := Value.fork Value.leaf (Value.fork t40 (Value.fork t39 (Value.fork Value.leaf (Value.fork (Value.stem (Value.fork Value.leaf (Value.stem t40))) (Value.fork (Value.stem (Value.fork Value.leaf (Value.stem t39))) t1)))))
noncomputable def t42 : Value := Value.stem t41
noncomputable def t43 : Value := Value.fork (Value.stem (Value.fork Value.leaf (Value.fork t37 (Value.fork t28 (Value.stem t42))))) t7
noncomputable def t44 : Value := Value.fork t6 (Value.stem t43)

/-- `fix` -/
noncomputable def fixV : Value := t14

/-- `fix x0 x1`, the whole application ⟶ a head split on `x0`: 29 reduce steps, 48 transitions. -/
noncomputable def fix_app : Rule := ⟨.reduce (.lit fixV) (.var 0) [.applyTo (.var 1)], .reduce (.var 0) (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t7)))) [.applyTo (.var 1)]⟩
theorem fix_app_check : checkRule fix_app 48 = true := by decide +kernel

/-- `fix x0` ⟶ a value: 16 reduce steps, 26 transitions. -/
noncomputable def fix_1 : Rule := ⟨.reduce (.lit fixV) (.var 0) [], .dispatch (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t7)))) []⟩
theorem fix_1_check : checkRule fix_1 26 = true := by decide +kernel

/-- What `fix x0` returns. -/
noncomputable def fix_1_out : SValue := (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t7))))

/-- `fix x0 x1` ⟶ a head split on `x0`: 13 reduce steps, 21 transitions. -/
noncomputable def fix_2 : Rule := ⟨.reduce fix_1_out (.var 1) [], .reduce (.var 0) (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t7)))) [.applyTo (.var 1)]⟩
theorem fix_2_check : checkRule fix_2 21 = true := by decide +kernel

/-- `fix__wait` -/
noncomputable def fix__waitV : Value := t18

/-- `fix__wait x0 x1`, the whole application ⟶ a head split on `x0`: 33 reduce steps, 55 transitions. -/
noncomputable def fix__wait_app : Rule := ⟨.reduce (.lit fix__waitV) (.var 0) [.applyTo (.var 1)], .reduce (.var 0) (.fork (.lit t15) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t16)))) [.applyTo (.var 1)]⟩
theorem fix__wait_app_check : checkRule fix__wait_app 55 = true := by decide +kernel

/-- `fix__wait x0` ⟶ a value: 16 reduce steps, 26 transitions. -/
noncomputable def fix__wait_1 : Rule := ⟨.reduce (.lit fix__waitV) (.var 0) [], .dispatch (.fork (.lit t15) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t16)))) []⟩
theorem fix__wait_1_check : checkRule fix__wait_1 26 = true := by decide +kernel

/-- What `fix__wait x0` returns. -/
noncomputable def fix__wait_1_out : SValue := (.fork (.lit t15) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t16))))

/-- `fix__wait x0 x1` ⟶ a head split on `x0`: 17 reduce steps, 28 transitions. -/
noncomputable def fix__wait_2 : Rule := ⟨.reduce fix__wait_1_out (.var 1) [], .reduce (.var 0) (.fork (.lit t15) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t16)))) [.applyTo (.var 1)]⟩
theorem fix__wait_2_check : checkRule fix__wait_2 28 = true := by decide +kernel

/-- `fix__naive` -/
noncomputable def fix__naiveV : Value := t23

/-- `fix__naive x0 x1`, the whole application ⟶ a head split on `x0`: 39 reduce steps, 65 transitions. -/
noncomputable def fix__naive_app : Rule := ⟨.reduce (.lit fix__naiveV) (.var 0) [.applyTo (.var 1)], .reduce (.var 0) (.fork (.lit t20) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t21)))) [.applyTo (.var 1)]⟩
theorem fix__naive_app_check : checkRule fix__naive_app 65 = true := by decide +kernel

/-- `fix__naive x0` ⟶ a value: 16 reduce steps, 26 transitions. -/
noncomputable def fix__naive_1 : Rule := ⟨.reduce (.lit fix__naiveV) (.var 0) [], .dispatch (.fork (.lit t20) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t21)))) []⟩
theorem fix__naive_1_check : checkRule fix__naive_1 26 = true := by decide +kernel

/-- What `fix__naive x0` returns. -/
noncomputable def fix__naive_1_out : SValue := (.fork (.lit t20) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t21))))

/-- `fix__naive x0 x1` ⟶ a head split on `x0`: 23 reduce steps, 38 transitions. -/
noncomputable def fix__naive_2 : Rule := ⟨.reduce fix__naive_1_out (.var 1) [], .reduce (.var 0) (.fork (.lit t20) (.fork (.lit .leaf) (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.lit t21)))) [.applyTo (.var 1)]⟩
theorem fix__naive_2_check : checkRule fix__naive_2 38 = true := by decide +kernel

/-- `let` -/
noncomputable def letV : Value := t24

/-- `let x0 x1`, the whole application ⟶ a head split on `x1`: 10 reduce steps, 17 transitions. -/
noncomputable def let_app : Rule := ⟨.reduce (.lit letV) (.var 0) [.applyTo (.var 1)], .reduce (.var 1) (.var 0) []⟩
theorem let_app_check : checkRule let_app 17 = true := by decide +kernel

/-- `let x0` ⟶ a value: 4 reduce steps, 6 transitions. -/
noncomputable def let_1 : Rule := ⟨.reduce (.lit letV) (.var 0) [], .dispatch (.fork (.lit t4) (.fork (.lit .leaf) (.var 0))) []⟩
theorem let_1_check : checkRule let_1 6 = true := by decide +kernel

/-- What `let x0` returns. -/
noncomputable def let_1_out : SValue := (.fork (.lit t4) (.fork (.lit .leaf) (.var 0)))

/-- `let x0 x1` ⟶ a head split on `x1`: 6 reduce steps, 10 transitions. -/
noncomputable def let_2 : Rule := ⟨.reduce let_1_out (.var 1) [], .reduce (.var 1) (.var 0) []⟩
theorem let_2_check : checkRule let_2 10 = true := by decide +kernel

/-- `wait` -/
noncomputable def waitV : Value := t31

/-- `wait x0 x1 x2`, the whole application ⟶ a head split on `x0`: 46 reduce steps, 77 transitions. -/
noncomputable def wait_app : Rule := ⟨.reduce (.lit waitV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2)], .reduce (.var 0) (.var 1) [.applyTo (.var 2)]⟩
theorem wait_app_check : checkRule wait_app 77 = true := by decide +kernel

/-- `wait x0` ⟶ a value: 34 reduce steps, 56 transitions. -/
noncomputable def wait_1 : Rule := ⟨.reduce (.lit waitV) (.var 0) [], .dispatch (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.var 0))))) (.lit t1)))))) (.lit t1)) []⟩
theorem wait_1_check : checkRule wait_1 56 = true := by decide +kernel

/-- What `wait x0` returns. -/
noncomputable def wait_1_out : SValue := (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.var 0))))) (.lit t1)))))) (.lit t1))

/-- `wait x0 x1` ⟶ a value: 4 reduce steps, 6 transitions. -/
noncomputable def wait_2 : Rule := ⟨.reduce wait_1_out (.var 1) [], .dispatch (.fork (.stem (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.var 0))))) (.lit t1))) (.fork (.lit .leaf) (.var 1))) []⟩
theorem wait_2_check : checkRule wait_2 6 = true := by decide +kernel

/-- What `wait x0 x1` returns. -/
noncomputable def wait_2_out : SValue := (.fork (.stem (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.var 0))))) (.lit t1))) (.fork (.lit .leaf) (.var 1)))

/-- `wait x0 x1 x2` ⟶ a head split on `x0`: 8 reduce steps, 13 transitions. -/
noncomputable def wait_3 : Rule := ⟨.reduce wait_2_out (.var 2) [], .reduce (.var 0) (.var 1) [.applyTo (.var 2)]⟩
theorem wait_3_check : checkRule wait_3 13 = true := by decide +kernel

/-- `:c` -/
noncomputable def p_cV : Value := t29

/-- `:c x0 x1 x2`, the whole application ⟶ a head split on `x0`: 22 reduce steps, 37 transitions. -/
noncomputable def p_c_app : Rule := ⟨.reduce (.lit p_cV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2)], .reduce (.var 0) (.var 2) [.applyTo (.var 1)]⟩
theorem p_c_app_check : checkRule p_c_app 37 = true := by decide +kernel

/-- `:c x0` ⟶ a value: 16 reduce steps, 26 transitions. -/
noncomputable def p_c_1 : Rule := ⟨.reduce (.lit p_cV) (.var 0) [], .dispatch (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.var 0))))) (.lit t1)) []⟩
theorem p_c_1_check : checkRule p_c_1 26 = true := by decide +kernel

/-- What `:c x0` returns. -/
noncomputable def p_c_1_out : SValue := (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.var 0))))) (.lit t1))

/-- `:c x0 x1` ⟶ a value: 4 reduce steps, 6 transitions. -/
noncomputable def p_c_2 : Rule := ⟨.reduce p_c_1_out (.var 1) [], .dispatch (.fork (.stem (.var 0)) (.fork (.lit .leaf) (.var 1))) []⟩
theorem p_c_2_check : checkRule p_c_2 6 = true := by decide +kernel

/-- What `:c x0 x1` returns. -/
noncomputable def p_c_2_out : SValue := (.fork (.stem (.var 0)) (.fork (.lit .leaf) (.var 1)))

/-- `:c x0 x1 x2` ⟶ a head split on `x0`: 2 reduce steps, 3 transitions. -/
noncomputable def p_c_3 : Rule := ⟨.reduce p_c_2_out (.var 2) [], .reduce (.var 0) (.var 2) [.applyTo (.var 1)]⟩
theorem p_c_3_check : checkRule p_c_3 3 = true := by decide +kernel

/-- `:b` -/
noncomputable def p_bV : Value := t12

/-- `:b x0 x1 x2`, the whole application ⟶ a head split on `x1`: 9 reduce steps, 15 transitions. -/
noncomputable def p_b_app : Rule := ⟨.reduce (.lit p_bV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2)], .reduce (.var 1) (.var 2) [.computeAndApply (.fork (.lit .leaf) (.var 0)) (.var 2)]⟩
theorem p_b_app_check : checkRule p_b_app 15 = true := by decide +kernel

/-- `:b x0` ⟶ a value: 7 reduce steps, 11 transitions. -/
noncomputable def p_b_1 : Rule := ⟨.reduce (.lit p_bV) (.var 0) [], .dispatch (.stem (.stem (.fork (.lit .leaf) (.var 0)))) []⟩
theorem p_b_1_check : checkRule p_b_1 11 = true := by decide +kernel

/-- What `:b x0` returns. -/
noncomputable def p_b_1_out : SValue := (.stem (.stem (.fork (.lit .leaf) (.var 0))))

/-- `:b x0 x1` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def p_b_2 : Rule := ⟨.reduce p_b_1_out (.var 1) [], .dispatch (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.var 1)) []⟩
theorem p_b_2_check : checkRule p_b_2 1 = true := by decide +kernel

/-- What `:b x0 x1` returns. -/
noncomputable def p_b_2_out : SValue := (.fork (.stem (.fork (.lit .leaf) (.var 0))) (.var 1))

/-- `:b x0 x1 x2` ⟶ a head split on `x1`: 1 reduce step, 1 transition. -/
noncomputable def p_b_3 : Rule := ⟨.reduce p_b_2_out (.var 2) [], .reduce (.var 1) (.var 2) [.computeAndApply (.fork (.lit .leaf) (.var 0)) (.var 2)]⟩
theorem p_b_3_check : checkRule p_b_3 1 = true := by decide +kernel

/-- `:s` -/
noncomputable def p_sV : Value := t10

/-- `:s x0 x1 x2`, the whole application ⟶ a head split on `x1`: 6 reduce steps, 10 transitions. -/
noncomputable def p_s_app : Rule := ⟨.reduce (.lit p_sV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2)], .reduce (.var 1) (.var 2) [.computeAndApply (.var 0) (.var 2)]⟩
theorem p_s_app_check : checkRule p_s_app 10 = true := by decide +kernel

/-- `:s x0` ⟶ a value: 4 reduce steps, 6 transitions. -/
noncomputable def p_s_1 : Rule := ⟨.reduce (.lit p_sV) (.var 0) [], .dispatch (.stem (.stem (.var 0))) []⟩
theorem p_s_1_check : checkRule p_s_1 6 = true := by decide +kernel

/-- What `:s x0` returns. -/
noncomputable def p_s_1_out : SValue := (.stem (.stem (.var 0)))

/-- `:s x0 x1` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def p_s_2 : Rule := ⟨.reduce p_s_1_out (.var 1) [], .dispatch (.fork (.stem (.var 0)) (.var 1)) []⟩
theorem p_s_2_check : checkRule p_s_2 1 = true := by decide +kernel

/-- What `:s x0 x1` returns. -/
noncomputable def p_s_2_out : SValue := (.fork (.stem (.var 0)) (.var 1))

/-- `:s x0 x1 x2` ⟶ a head split on `x1`: 1 reduce step, 1 transition. -/
noncomputable def p_s_3 : Rule := ⟨.reduce p_s_2_out (.var 2) [], .reduce (.var 1) (.var 2) [.computeAndApply (.var 0) (.var 2)]⟩
theorem p_s_3_check : checkRule p_s_3 1 = true := by decide +kernel

/-- `:k` -/
noncomputable def p_kV : Value := t1

/-- `:k x0 x1`, the whole application ⟶ a value: 2 reduce steps, 3 transitions. -/
noncomputable def p_k_app : Rule := ⟨.reduce (.lit p_kV) (.var 0) [.applyTo (.var 1)], .dispatch (.var 0) []⟩
theorem p_k_app_check : checkRule p_k_app 3 = true := by decide +kernel

/-- `:k x0` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def p_k_1 : Rule := ⟨.reduce (.lit p_kV) (.var 0) [], .dispatch (.fork (.lit .leaf) (.var 0)) []⟩
theorem p_k_1_check : checkRule p_k_1 1 = true := by decide +kernel

/-- What `:k x0` returns. -/
noncomputable def p_k_1_out : SValue := (.fork (.lit .leaf) (.var 0))

/-- `:k x0 x1` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def p_k_2 : Rule := ⟨.reduce p_k_1_out (.var 1) [], .dispatch (.var 0) []⟩
theorem p_k_2_check : checkRule p_k_2 1 = true := by decide +kernel

/-- What `:k x0 x1` returns. -/
noncomputable def p_k_2_out : SValue := (.var 0)

/-- `:i` -/
noncomputable def p_iV : Value := t3

/-- `:i x0` ⟶ a value: 4 reduce steps, 6 transitions. -/
noncomputable def p_i_1 : Rule := ⟨.reduce (.lit p_iV) (.var 0) [], .dispatch (.var 0) []⟩
theorem p_i_1_check : checkRule p_i_1 6 = true := by decide +kernel

/-- What `:i x0` returns. -/
noncomputable def p_i_1_out : SValue := (.var 0)

/-- `:ct` -/
noncomputable def p_ctV : Value := t2

/-- `:ct x0 x1`, the whole application ⟶ a head split on `x0`: 2 reduce steps, 3 transitions. -/
noncomputable def p_ct_app : Rule := ⟨.reduce (.lit p_ctV) (.var 0) [.applyTo (.var 1)], .reduce (.var 0) (.var 1) [.computeAndApply (.lit .leaf) (.var 1)]⟩
theorem p_ct_app_check : checkRule p_ct_app 3 = true := by decide +kernel

/-- `:ct x0` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def p_ct_1 : Rule := ⟨.reduce (.lit p_ctV) (.var 0) [], .dispatch (.fork (.lit p_kV) (.var 0)) []⟩
theorem p_ct_1_check : checkRule p_ct_1 1 = true := by decide +kernel

/-- What `:ct x0` returns. -/
noncomputable def p_ct_1_out : SValue := (.fork (.lit p_kV) (.var 0))

/-- `:ct x0 x1` ⟶ a head split on `x0`: 1 reduce step, 1 transition. -/
noncomputable def p_ct_2 : Rule := ⟨.reduce p_ct_1_out (.var 1) [], .reduce (.var 0) (.var 1) [.computeAndApply (.lit .leaf) (.var 1)]⟩
theorem p_ct_2_check : checkRule p_ct_2 1 = true := by decide +kernel

/-- `self_apply` -/
noncomputable def self_applyV : Value := t19

/-- `self_apply x0` ⟶ a head split on `x0`: 9 reduce steps, 15 transitions. -/
noncomputable def self_apply_1 : Rule := ⟨.reduce (.lit self_applyV) (.var 0) [], .reduce (.var 0) (.var 0) []⟩
theorem self_apply_1_check : checkRule self_apply_1 15 = true := by decide +kernel

/-- `triage` -/
noncomputable def triageV : Value := t33

/-- `triage x0 x1 x2 x3`, the whole application ⟶ a arg split on `x3`: 9 reduce steps, 16 transitions. -/
noncomputable def triage_app : Rule := ⟨.reduce (.lit triageV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2), .applyTo (.var 3)], .reduce (.fork (.fork (.var 0) (.var 1)) (.var 2)) (.var 3) []⟩
theorem triage_app_check : checkRule triage_app 16 = true := by decide +kernel

/-- `triage x0` ⟶ a value: 4 reduce steps, 6 transitions. -/
noncomputable def triage_1 : Rule := ⟨.reduce (.lit triageV) (.var 0) [], .dispatch (.fork (.lit t9) (.stem (.var 0))) []⟩
theorem triage_1_check : checkRule triage_1 6 = true := by decide +kernel

/-- What `triage x0` returns. -/
noncomputable def triage_1_out : SValue := (.fork (.lit t9) (.stem (.var 0)))

/-- `triage x0 x1` ⟶ a value: 4 reduce steps, 6 transitions. -/
noncomputable def triage_2 : Rule := ⟨.reduce triage_1_out (.var 1) [], .dispatch (.stem (.fork (.var 0) (.var 1))) []⟩
theorem triage_2_check : checkRule triage_2 6 = true := by decide +kernel

/-- What `triage x0 x1` returns. -/
noncomputable def triage_2_out : SValue := (.stem (.fork (.var 0) (.var 1)))

/-- `triage x0 x1 x2` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def triage_3 : Rule := ⟨.reduce triage_2_out (.var 2) [], .dispatch (.fork (.fork (.var 0) (.var 1)) (.var 2)) []⟩
theorem triage_3_check : checkRule triage_3 1 = true := by decide +kernel

/-- What `triage x0 x1 x2` returns. -/
noncomputable def triage_3_out : SValue := (.fork (.fork (.var 0) (.var 1)) (.var 2))

/-- `triage x0 x1 x2 x3`, by the shape of `x3` (△, △ _, △ _ _). -/
noncomputable def triage_4_tree : RuleTree := .split 3 4
  (.leaf (.dispatch (.var 0) []) 1)
  (.leaf (.reduce (.var 1) (.var 4) []) 1)
  (.leaf (.reduce (.var 2) (.var 4) [.applyTo (.var 5)]) 1)
theorem triage_4_tree_check : checkRules (triage_4_tree.rules (.reduce triage_3_out (.var 3) [])) = true := by decide +kernel

/-- `Bool.match` -/
noncomputable def Bool_matchV : Value := t34

/-- `Bool.match x0 x1 x2`, the whole application ⟶ a arg split on `x2`: 50 reduce steps, 84 transitions. -/
noncomputable def Bool_match_app : Rule := ⟨.reduce (.lit Bool_matchV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2)], .reduce (.fork (.fork (.var 0) (.fork (.lit .leaf) (.var 1))) (.lit .leaf)) (.var 2) []⟩
theorem Bool_match_app_check : checkRule Bool_match_app 84 = true := by decide +kernel

/-- `Bool.match x0` ⟶ a value: 40 reduce steps, 66 transitions. -/
noncomputable def Bool_match_1 : Rule := ⟨.reduce (.lit Bool_matchV) (.var 0) [], .dispatch (.fork (.stem (.fork (.stem (.fork (.lit .leaf) (.fork (.lit t9) (.stem (.var 0))))) (.lit p_kV))) (.fork (.lit .leaf) (.lit .leaf))) []⟩
theorem Bool_match_1_check : checkRule Bool_match_1 66 = true := by decide +kernel

/-- What `Bool.match x0` returns. -/
noncomputable def Bool_match_1_out : SValue := (.fork (.stem (.fork (.stem (.fork (.lit .leaf) (.fork (.lit t9) (.stem (.var 0))))) (.lit p_kV))) (.fork (.lit .leaf) (.lit .leaf)))

/-- `Bool.match x0 x1` ⟶ a value: 10 reduce steps, 16 transitions. -/
noncomputable def Bool_match_2 : Rule := ⟨.reduce Bool_match_1_out (.var 1) [], .dispatch (.fork (.fork (.var 0) (.fork (.lit .leaf) (.var 1))) (.lit .leaf)) []⟩
theorem Bool_match_2_check : checkRule Bool_match_2 16 = true := by decide +kernel

/-- What `Bool.match x0 x1` returns. -/
noncomputable def Bool_match_2_out : SValue := (.fork (.fork (.var 0) (.fork (.lit .leaf) (.var 1))) (.lit .leaf))

/-- `Bool.match x0 x1 x2`, by the shape of `x2` (△, △ _, △ _ _). -/
noncomputable def Bool_match_3_tree : RuleTree := .split 2 3
  (.leaf (.dispatch (.var 0) []) 1)
  (.leaf (.dispatch (.var 1) []) 2)
  (.leaf (.dispatch (.fork (.var 3) (.var 4)) []) 4)
theorem Bool_match_3_tree_check : checkRules (Bool_match_3_tree.rules (.reduce Bool_match_2_out (.var 2) [])) = true := by decide +kernel

/-- `List.match` -/
noncomputable def List_matchV : Value := t35

/-- `List.match x0 x1 x2`, the whole application ⟶ a arg split on `x2`: 11 reduce steps, 19 transitions. -/
noncomputable def List_match_app : Rule := ⟨.reduce (.lit List_matchV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2)], .reduce (.fork (.fork (.var 0) (.lit .leaf)) (.var 1)) (.var 2) []⟩
theorem List_match_app_check : checkRule List_match_app 19 = true := by decide +kernel

/-- `List.match x0` ⟶ a value: 10 reduce steps, 16 transitions. -/
noncomputable def List_match_1 : Rule := ⟨.reduce (.lit List_matchV) (.var 0) [], .dispatch (.stem (.fork (.var 0) (.lit .leaf))) []⟩
theorem List_match_1_check : checkRule List_match_1 16 = true := by decide +kernel

/-- What `List.match x0` returns. -/
noncomputable def List_match_1_out : SValue := (.stem (.fork (.var 0) (.lit .leaf)))

/-- `List.match x0 x1` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def List_match_2 : Rule := ⟨.reduce List_match_1_out (.var 1) [], .dispatch (.fork (.fork (.var 0) (.lit .leaf)) (.var 1)) []⟩
theorem List_match_2_check : checkRule List_match_2 1 = true := by decide +kernel

/-- What `List.match x0 x1` returns. -/
noncomputable def List_match_2_out : SValue := (.fork (.fork (.var 0) (.lit .leaf)) (.var 1))

/-- `List.match x0 x1 x2`, by the shape of `x2` (△, △ _, △ _ _). -/
noncomputable def List_match_3_tree : RuleTree := .split 2 3
  (.leaf (.dispatch (.var 0) []) 1)
  (.leaf (.dispatch (.stem (.var 3)) []) 2)
  (.leaf (.reduce (.var 1) (.var 3) [.applyTo (.var 4)]) 1)
theorem List_match_3_tree_check : checkRules (List_match_3_tree.rules (.reduce List_match_2_out (.var 2) [])) = true := by decide +kernel

/-- `Option.match` -/
noncomputable def Option_matchV : Value := t36

/-- `Option.match x0 x1 x2`, the whole application ⟶ a arg split on `x2`: 35 reduce steps, 59 transitions. -/
noncomputable def Option_match_app : Rule := ⟨.reduce (.lit Option_matchV) (.var 0) [.applyTo (.var 1), .applyTo (.var 2)], .reduce (.fork (.fork (.var 0) (.var 1)) (.lit .leaf)) (.var 2) []⟩
theorem Option_match_app_check : checkRule Option_match_app 59 = true := by decide +kernel

/-- `Option.match x0` ⟶ a value: 28 reduce steps, 46 transitions. -/
noncomputable def Option_match_1 : Rule := ⟨.reduce (.lit Option_matchV) (.var 0) [], .dispatch (.fork (.stem (.fork (.lit t9) (.stem (.var 0)))) (.fork (.lit .leaf) (.lit .leaf))) []⟩
theorem Option_match_1_check : checkRule Option_match_1 46 = true := by decide +kernel

/-- What `Option.match x0` returns. -/
noncomputable def Option_match_1_out : SValue := (.fork (.stem (.fork (.lit t9) (.stem (.var 0)))) (.fork (.lit .leaf) (.lit .leaf)))

/-- `Option.match x0 x1` ⟶ a value: 7 reduce steps, 11 transitions. -/
noncomputable def Option_match_2 : Rule := ⟨.reduce Option_match_1_out (.var 1) [], .dispatch (.fork (.fork (.var 0) (.var 1)) (.lit .leaf)) []⟩
theorem Option_match_2_check : checkRule Option_match_2 11 = true := by decide +kernel

/-- What `Option.match x0 x1` returns. -/
noncomputable def Option_match_2_out : SValue := (.fork (.fork (.var 0) (.var 1)) (.lit .leaf))

/-- `Option.match x0 x1 x2`, by the shape of `x2` (△, △ _, △ _ _). -/
noncomputable def Option_match_3_tree : RuleTree := .split 2 3
  (.leaf (.dispatch (.var 0) []) 1)
  (.leaf (.reduce (.var 1) (.var 3) []) 1)
  (.leaf (.dispatch (.fork (.var 3) (.var 4)) []) 4)
theorem Option_match_3_tree_check : checkRules (Option_match_3_tree.rules (.reduce Option_match_2_out (.var 2) [])) = true := by decide +kernel

/-- `Pair.match` -/
noncomputable def Pair_matchV : Value := t9

/-- `Pair.match x0 x1`, the whole application ⟶ a arg split on `x1`: 1 reduce step, 2 transitions. -/
noncomputable def Pair_match_app : Rule := ⟨.reduce (.lit Pair_matchV) (.var 0) [.applyTo (.var 1)], .reduce (.fork (.lit t5) (.var 0)) (.var 1) []⟩
theorem Pair_match_app_check : checkRule Pair_match_app 2 = true := by decide +kernel

/-- `Pair.match x0` ⟶ a value: 1 reduce step, 1 transition. -/
noncomputable def Pair_match_1 : Rule := ⟨.reduce (.lit Pair_matchV) (.var 0) [], .dispatch (.fork (.lit t5) (.var 0)) []⟩
theorem Pair_match_1_check : checkRule Pair_match_1 1 = true := by decide +kernel

/-- What `Pair.match x0` returns. -/
noncomputable def Pair_match_1_out : SValue := (.fork (.lit t5) (.var 0))

/-- `Pair.match x0 x1`, by the shape of `x1` (△, △ _, △ _ _). -/
noncomputable def Pair_match_2_tree : RuleTree := .split 1 2
  (.leaf (.dispatch (.lit .leaf) []) 1)
  (.leaf (.dispatch (.stem (.var 2)) []) 2)
  (.leaf (.reduce (.var 0) (.var 2) [.applyTo (.var 3)]) 1)
theorem Pair_match_2_tree_check : checkRules (Pair_match_2_tree.rules (.reduce Pair_match_1_out (.var 1) [])) = true := by decide +kernel

/-- `List.map` -/
noncomputable def List_mapV : Value := t38

/-- `List.map x0 x1`, the whole application ⟶ a arg split on `x1`: 63 reduce steps, 105 transitions. -/
noncomputable def List_map_app : Rule := ⟨.reduce (.lit List_mapV) (.var 0) [.applyTo (.var 1)], .reduce (.fork (.lit t5) (.fork (.stem (.fork (.lit t27) (.fork (.lit Pair_matchV) (.var 0)))) (.fork (.lit .leaf) (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.fork (.lit t37) (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.fork (.lit t27) (.fork (.lit Pair_matchV) (.var 0))))))) (.lit p_kV))))) (.lit t7))))))) (.var 1) []⟩
theorem List_map_app_check : checkRule List_map_app 105 = true := by decide +kernel

/-- `List.map x0` ⟶ a value: 43 reduce steps, 71 transitions. -/
noncomputable def List_map_1 : Rule := ⟨.reduce (.lit List_mapV) (.var 0) [], .dispatch (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.fork (.lit t37) (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.fork (.lit t27) (.fork (.lit Pair_matchV) (.var 0))))))) (.lit p_kV))))) (.lit t7)))) []⟩
theorem List_map_1_check : checkRule List_map_1 71 = true := by decide +kernel

/-- What `List.map x0` returns. -/
noncomputable def List_map_1_out : SValue := (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.fork (.lit t37) (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.fork (.lit t27) (.fork (.lit Pair_matchV) (.var 0))))))) (.lit p_kV))))) (.lit t7))))

/-- `List.map x0 x1`, by the shape of `x1` (△, △ _, △ _ _). -/
noncomputable def List_map_2_tree : RuleTree := .split 1 2
  (.leaf (.dispatch (.lit .leaf) []) 34)
  (.leaf (.dispatch (.stem (.var 2)) []) 35)
  (.leaf (.reduce (.var 0) (.var 2) [.computeAndApply (.lit t5) (.var 2), .computeAndApply (.lit t26) (.var 2), .applyTo (.fork (.lit t6) (.stem (.fork (.stem (.fork (.lit .leaf) (.fork (.lit t37) (.fork (.stem (.fork (.lit .leaf) (.stem (.stem (.fork (.lit t27) (.fork (.lit Pair_matchV) (.var 0))))))) (.lit p_kV))))) (.lit t7)))), .applyTo (.var 3)]) 39)
theorem List_map_2_tree_check : checkRules (List_map_2_tree.rules (.reduce List_map_1_out (.var 1) [])) = true := by decide +kernel

/-- `List.length` -/
noncomputable def List_lengthV : Value := t44

/-- `List.length x0`, by the shape of `x0` (△, △ _, △ _ _). -/
noncomputable def List_length_1_tree : RuleTree := .split 0 1
  (.leaf (.dispatch (.lit .leaf) []) 34)
  (.leaf (.dispatch (.stem (.var 1)) []) 35)
  (.leaf (.reduce (.fork (.lit t5) (.fork (.lit .leaf) (.fork (.lit t42) (.fork (.lit t6) (.stem (.lit t43)))))) (.var 2) [.computeAndApply (.lit t41) (.var 2)]) 70)
theorem List_length_1_tree_check : checkRules (List_length_1_tree.rules (.reduce (.lit List_lengthV) (.var 0) [])) = true := by decide +kernel

/-- Every rule above, checked. -/
noncomputable def all : List Checked := [
  .one fix_app_check,
  .one fix_1_check,
  .one fix_2_check,
  .one fix__wait_app_check,
  .one fix__wait_1_check,
  .one fix__wait_2_check,
  .one fix__naive_app_check,
  .one fix__naive_1_check,
  .one fix__naive_2_check,
  .one let_app_check,
  .one let_1_check,
  .one let_2_check,
  .one wait_app_check,
  .one wait_1_check,
  .one wait_2_check,
  .one wait_3_check,
  .one p_c_app_check,
  .one p_c_1_check,
  .one p_c_2_check,
  .one p_c_3_check,
  .one p_b_app_check,
  .one p_b_1_check,
  .one p_b_2_check,
  .one p_b_3_check,
  .one p_s_app_check,
  .one p_s_1_check,
  .one p_s_2_check,
  .one p_s_3_check,
  .one p_k_app_check,
  .one p_k_1_check,
  .one p_k_2_check,
  .one p_i_1_check,
  .one p_ct_app_check,
  .one p_ct_1_check,
  .one p_ct_2_check,
  .one self_apply_1_check,
  .one triage_app_check,
  .one triage_1_check,
  .one triage_2_check,
  .one triage_3_check,
  ⟨_, triage_4_tree_check⟩,
  .one Bool_match_app_check,
  .one Bool_match_1_check,
  .one Bool_match_2_check,
  ⟨_, Bool_match_3_tree_check⟩,
  .one List_match_app_check,
  .one List_match_1_check,
  .one List_match_2_check,
  ⟨_, List_match_3_tree_check⟩,
  .one Option_match_app_check,
  .one Option_match_1_check,
  .one Option_match_2_check,
  ⟨_, Option_match_3_tree_check⟩,
  .one Pair_match_app_check,
  .one Pair_match_1_check,
  ⟨_, Pair_match_2_tree_check⟩,
  .one List_map_app_check,
  .one List_map_1_check,
  ⟨_, List_map_2_tree_check⟩,
  ⟨_, List_length_1_tree_check⟩]

end Rules.Core
